import esbuild from "esbuild";
import { builtinModules } from "node:module";
import { copyFileSync, existsSync, mkdirSync } from "node:fs";
import { resolve, join } from "node:path";

const prod = process.argv[2] === "production";
const root = resolve(import.meta.dirname, "../..");
const pluginRoot = import.meta.dirname;
const outdir = pluginRoot;
const testVaultPluginDir = process.env.OBE_SMOKE_PLUGIN_DIR;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const copyAssetsPlugin = {
  name: "copy-assets",
  setup(build) {
    build.onEnd((result) => {
      if (result.errors.length > 0) return;
      copyFileSync(resolve(pluginRoot, "manifest.json"), resolve(outdir, "manifest.json"));
      copyFileSync(resolve(root, "packages/obsidian/src/styles.css"), resolve(outdir, "styles.css"));
      if (testVaultPluginDir) {
        mkdirSync(testVaultPluginDir, { recursive: true });
        for (const file of ["main.js", "manifest.json", "styles.css"]) {
          const source = resolve(outdir, file);
          if (existsSync(source)) copyFileSync(source, join(testVaultPluginDir, file));
        }
        console.log(`Copied smoke plugin to ${testVaultPluginDir}`);
      }
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: [resolve(pluginRoot, "src/main.ts")],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/*",
    ...builtinModules,
    ...builtinModules.map((moduleName) => `node:${moduleName}`),
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  outfile: resolve(outdir, "main.js"),
  minify: prod,
  treeShaking: true,
  plugins: [copyAssetsPlugin],
});

if (prod) {
  await context.rebuild();
  await context.dispose();
  process.exit(0);
}

await context.watch();
